config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  root 'static_pages#home'

  get '/admin_panel' => 'static_pages#admin_panel'
  get '/report' => 'static_pages#report'
  get '/result' => 'static_pages#result'
  get '/analytics' => 'static_pages#analytics'
  get '/recent_updates' => 'static_pages#recent_updates'

  devise_for :users
  resources :projects do
    resources :project_phases
    resources :project_components
    resources :project_images
  end
  scope "/admin" do
    resources :users
  end
  resources :universities do
    collection do
      match 'search' => 'universities#search', via: [:get, :post], as: :search
    end
  end
  resources :static_pages do
    collection do
      match 'search' => 'static_pages#search', via: [:get, :post], as: :search
      match 'search_report' => 'static_pages#search_report', via: [:get, :post], as: :search_report
      match 'search_analytics' => 'static_pages#search_analytics', via: [:get, :post], as: :search_analytics
      match 'search_users' => 'static_pages#search_users', via: [:get, :post], as: :search_users
    end
  end
  resources :project_statuses
  resources :project_classifications
  resources :fund_sources

  namespace :api do
    api version: 1, module: 'v1' do
      resources :sessions, only: [:create]
      resources :universities, only: [:index, :show]
      resources :projects, only: [:index, :show] do
        resources :project_components, only: [:index, :show]
        resources :project_phases, only: [:index, :show]
        resources :project_images, only: [:index, :show]
      end
    end
  end

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	before_action :authenticate_user!, only: [:admin_panel]

	def home
		@q = Project.ransack(params[:q])
		@projects = @q.result.paginate(:page => params[:page], :per_page => 10)
	end

	def result
		@q = Project.ransack(params[:q])
		@projects = @q.result.paginate(:page => params[:page], :per_page => 10)
	end

	def admin_panel
		@q = User.ransack(params[:q])
		@users = @q.result.paginate(:page => params[:page], :per_page => 15)
	end

	def report
		@q = Project.ransack(params[:q])
		@projects = @q.result
		respond_to do |format|
	      format.html
	      format.xlsx {
	        render xlsx: "report", filename: "reports.xlsx"
	      }
	    end
	end

	def analytics
		@q = Project.ransack(params[:q])
		@output = @q.result
		@projects = @output.paginate(:page => params[:page], :per_page => 10)

		@group_by_cu = @output.group_by{ |x| x[:university_id] }.map {|k,v| [University.find(k).university_name, v.length]}
		@group_by_status = @output.group_by{ |x| x[:status] }.map {|k,v| [(ProjectStatus.find(k).description rescue nil), v.length]} 
		@group_by_pc = @output.group_by{ |x| x[:classification] }.map {|k,v| [(ProjectClassification.find(k).description rescue nil), v.length]}
		@budget_distribution_per_cu = @output.group(:university_id).order('university_id asc').sum(:financial_budget)

		@group_by_funds = @output.joins(:funds).group("funds.fund_source").count
		@group_by_fund_name = @group_by_funds.map{|k,v| [(FundSource.find(k).source_name rescue nil), v]}.sort_by{|x| x[0]}
		@group_by_fund_classification = @group_by_funds.map{|k,v| [(FundSource.find(k).fund_source_classification rescue nil), v]}

		@group_by_fund_classification = @group_by_fund_classification.inject(Hash.new(0)) do |result, itm|
		  result[itm.first] += itm.last
		  result
		end.to_a.sort_by{|k| k[0]}

		@status_vs_src_vs_classification = []
		ProjectStatus.find_each do |status|
			@status_vs_src_vs_classification << {:name => status.description, :data => @output.where( status: status.id ).joins(:fund_sources).group("fund_sources.fund_source_classification").order('fund_sources.fund_source_classification asc').sum(:financial_budget)}
		end
		@status_vs_src_vs_classification_percent = []
		ProjectStatus.find_each do |status|
			total_count = Project.joins(:fund_sources).group("fund_sources.fund_source_classification").order('fund_sources.fund_source_classification asc').count
			classification_count = @output.where( status: status.id ).joins(:fund_sources).group("fund_sources.fund_source_classification").order('fund_sources.fund_source_classification asc').count
			@status_vs_src_vs_classification_percent << {:name => status.description, :data => classification_count.map {|k,v| [ k, (100*v/total_count[k].to_f).round(2) ]} }
		end
		@status_vs_src_vs_classification_count = []
		ProjectStatus.find_each do |status|
			total_count = Project.joins(:fund_sources).group("fund_sources.fund_source_classification").order('fund_sources.fund_source_classification asc').count
			classification_count = @output.where( status: status.id ).joins(:fund_sources).group("fund_sources.fund_source_classification").order('fund_sources.fund_source_classification asc').count
			@status_vs_src_vs_classification_count << {:name => status.description, :data => classification_count }
		end
	end

	def recent_updates
		@activities = PublicActivity::Activity.all.order('created_at DESC').limit(30)
	end

	def search_users
		admin_panel
		render :admin_panel
	end

	def search_analytics
		analytics
		render :analytics
	end

	def search_report
		@q = Project.ransack(params[:q])
		@projects = @q.result
		render :report
	end

	def search
		result
		render :result
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_search.html.erb
<div class="row">	
	<div id="accordion" class="panel panel-info">
		<div class="panel-heading">
			<b><a class="accordion-toggle" data-toggle="collapse" data-target="#collapseSearch" href="#collapseSearch"><%= icon('search')%> Search:</a></b>
		</div>
		<div id="collapseSearch" class="panel-collapse collapse in">
			<div class="panel-body">
				<%= search_form_for @q, url: search_static_pages_path do |f| %>
					<div class="row">
						<div class="col-xs-2">
				  			<%= f.input :project_code_cont, :label => "Project Code:" %>
				  		</div>
				  		<div class="col-xs-5">
				  			<%= f.input :project_name_cont, :label => "Project Title:" %>
				  		</div>
				  		<div class="col-xs-5">
				  			<%= f.input :description_cont, :label => "Project Description:" %>
				  		</div>
				  	</div>
				  	<div class="row">
				  		<div class="col-xs-6">
				  			<%= f.input :bidding_contractor_cont, :label => "Contractor/s:" %>
				  		</div>
				  		<div class="col-xs-6">
				  			<%= f.input :financial_source_cont, :label => "Source of fund/s:" %>
				  		</div>
				  	</div>
				  	<div class="row">
				  		<div class="col-xs-3">
				  			<%= f.input :financial_budget_gteq, :label => "Min. Budget" %>
				  		</div>
				  		<div class="col-xs-3">
				  			<%= f.input :financial_budget_lteq, :label => "Max. Budget" %>
				  		</div>
				  		<div class="col-xs-3">
				  			<%= f.input :percent_accomplishment_gteq, :label => "Min. % Accomplishment" %>
				  		</div>
				  		<div class="col-xs-3">
				  			<%= f.input :percent_accomplishment_lteq, :label => "Max. % Accomplishment" %>
				  		</div>
				  	</div>
				  <%= f.button :submit, :class => "btn btn-success pull-right" %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/static_pages/_signin.html.erb
<div class="row">
	<div class="col-xs-2">
	</div>
	<div class="col-xs-8">
		<div class="login-panel panel panel-default">
			<div class="panel-heading text-center" style="background-color: #094424 !important;">
				<%= image_tag "upseal.png", :class => "img-responsive center-image"  %>
				<h3 style="color: #F1A92C;">Office of the Vice President for Development</h3>
				<h4 style="color: #F1A92C;">Data Collection and Reporting System</h4>
				<h5 style="color: #F1A92C;">OVPDCARES:INFRASTRUCTURE PROJECTS</h5>
			</div>
			<div class="panel-body">
				<%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
				  <div class="form-inputs">
				    <%= f.input :email, required: false, autofocus: true, placeholder: 'Email', label: false %>
				    <%= f.input :password, required: false, placeholder: 'Password', label: false %>
				  </div>

				  <div class="form-actions text-center">
				    <%= f.button :submit, "Log in", :class => "btn btn-success btn-block" %>
				  </div>
				<% end %>
			</div>
		</div>
	</div>
	<div class="col-xs-2">
	</div>
</div>

app/views/static_pages/admin_panel.html.erb
<h1><b>Administrator Panel</b></h1>
<div class="jumbotron">
<%= search_form_for @q, url: search_users_static_pages_path do |f| %>
	<div class="row">
  		<div class="col-xs-6">
  			<%= f.input :first_name_cont, :label => "First Name", required: false %>
  		</div>
  		<div class="col-xs-6">
  			<%= f.input :last_name_cont, :label => "Last Name", required: false %>
  		</div>
  		<div class="col-xs-6">
  			<%= f.input :email_cont, :label => "Email", required: false %>
  		</div>
  		<div class="col-xs-3">
  			<%= f.input :admin_eq, :label => "Is Admin?", as: :select, required: false %>
  		</div>
  		<div class="col-xs-3">
  			<%= f.input :approved_eq, :label => "Is Approved?", as: :select, required: false %>
  		</div>
  	</div>
 	<%= f.button :submit, :class => "btn btn-success pull-right" %>
<% end %>
</div>
<div class="row">
	<div class="col-xs-12">
		<%= link_to '<i class="fa fa-user-plus"></i> Create new user'.html_safe, new_user_path, :class => "pull-right" %>
		<table class="table table-hover table-responsive">
			<thead>
				<tr>
					<th>Email</th>
					<th>First Name</th>
					<th>Last Name</th>
					<th>Is Admin?</th>
					<th>Is Approved?</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<% @users.each do |user| %>
					<tr>
						<td><%= user.email %></td>
						<td><%= user.first_name %></td>
						<td><%= user.last_name %></td>
						<td><%= user.admin %></td>
						<td><%= user.approved %></td>
						<td> <%= link_to "Edit", edit_user_path(user) %> | <%= link_to "Delete", user, data: { confirm: 'Delete this user?' }, :method => :delete %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>
<div class="text-center">
  	<%= will_paginate @users, renderer: BootstrapPagination::Rails %>
</div>

app/views/static_pages/analytics.html.erb
<h1><b>Analytics Generation Module</b></h1>
<div class="jumbotron">
<%= search_form_for @q, url: search_analytics_static_pages_path do |f| %>
	<div class="row">
  		<div class="col-xs-4">
  			<%= f.input :status_eq, :collection => ProjectStatus.all, :label_method => :description, :include_blank => true, :label => "Project Status", required: false %>
  		</div>
  		<div class="col-xs-4">
  			<%= f.input :timeline_actual_end_gteq, :label => "From Completion Date:", :start_year => Date.today.year, :end_year => 1900, :include_blank => true, :as => :date_picker, :placeholder => "DD/MM/YYYY", required: false %>
  		</div>
  		<div class="col-xs-4">
  			<%= f.input :timeline_actual_end_lteq, :label => "To Completion Date:", :start_year => Date.today.year, :end_year => 1900, :include_blank => true, :as => :date_picker, :placeholder => "DD/MM/YYYY", required: false %>
  		</div>
  	</div>
  	<div class="row">
  		<div class="col-xs-6">
  			<%= f.input :university_id_in, :collection => University.all.order(:university_name), :label_method => :university_name, :include_blank => true, :label => "Project of:", required: false %>
  		</div>
  		<div class="col-xs-6">
  			<%= f.input :funds_fund_source_in, :collection => FundSource.all.order(:source_name), :label_method => :source_name, :include_blank => true, :label => "Source of fund/s:", required: false %>
  		</div>
  	</div>
  	
  <%= f.button :submit, :class => "btn btn-success pull-right" %>
<% end %>
</div>

<div class="col-xs-12">
	<div class="panel panel-info">
		<div class="panel-heading">
			<h3>Number of Projects: <%= @output.count %></h3>	
		</div>
		<div class="panel-body">

			<h2><b>System-wide:</b></h2>

			<b><u>Budget Distribution per CU:</u></b><br>
			<div class="jumbotron">
				<b><li>Total (PhP): <%= number_with_precision( @output.sum(:financial_budget), precision: 2, delimiter: ',' ) %></li></b><br>
				<%= pie_chart @budget_distribution_per_cu.map { |k, v| [University.find(k).university_name, number_with_precision( v/BigDecimal.new("1000000"), precision: 3 )] } %>
			</div>

			<b><u>Project Distribution per CU:</u></b><br>
			<div class="jumbotron">
				<%= pie_chart @group_by_cu %>
			</div>

			<b><u>Project Status vs Source of Funding:</u></b><br>
			<div class="jumbotron">
				<b><u>By Budget:</u></b><br>
				<%= column_chart @status_vs_src_vs_classification %>
				<b><u>Percentages:</u></b><br>
				<%= column_chart @status_vs_src_vs_classification_percent, stacked: true %>
				<b><u>Raw Numbers:</u></b><br>
				<%= column_chart @status_vs_src_vs_classification_count, stacked: true %>
			</div>

			<b><u>Project Status:</u></b><br>
			<div class="jumbotron">
				<%= pie_chart @group_by_status %>
			</div>

			<b><u>Project Funding:</u></b><br>
			<div class="jumbotron">
				<%= pie_chart @group_by_fund_classification %>
				<%= pie_chart @group_by_fund_name %>
			</div>

			<b><u>Sorted by Project Classification:</u></b><br>
			<div class="jumbotron">
				<%= pie_chart @group_by_pc %>
			</div>

			<b><u>Sorted by Budget:</u></b><br>
			<div class="jumbotron">
				<b><li>Total (PhP): <%= number_with_precision( @output.sum(:financial_budget), precision: 2, delimiter: ',' ) %></li></b><br>
				<%= pie_chart @output.group(:project_name).order('financial_budget desc').sum(:financial_budget) %>
			</div>

			<%= render 'shared/projects_list' %>
		</div>
	</div>
</div>

app/views/static_pages/home.html.erb
<br>
<div class="row">
	<div class="jumbotron">
		<div class="row">
			<div class="text-center">
				<%= image_tag "upseal_home.png", :class => "img-responsive center-image" %>
			</div>
			<div class="text-justify">
				Welcome to the Office of the Vice President for Development's Data Reporting and Collection System or OVPDCares for Infrastructure Projects. The system serves as a digital hub for infrastructure-related information across all constituent universities of the University of the Philippines.
			</div>
		</div>
	</div>
</div>
<div class="row row-eq-height">
	<div class="well well-dynamic col-xs-6">
		<%= render 'shared/university_selector' %>
		<div class="text-justify">
			Navigate through the system and select which CU's infrastructure projects you wish to view. Viewing your home CU allows you to add and edit infrastructure project-related information.
		</div>
	</div>
	<div class="well well-dynamic col-xs-6">
		<%= link_to "Generate reports", report_path, :class => "btn btn-success col-xs-12" %>
		<div class="row">
		</div>
		<div class="text-justify">
			Generate a list of infrastructure projects according to their Project Status, Time of Completion, and Assigned CU.
		</div>
	</div>
</div>
<div class="row">
	<div class="well">
		<div class="text-justify">
			Quickly look for related infrastructure projects by sorting through their Project Title, Project Status, Assigned CU, and Source of Funds, among others.
		</div>
		<%= render 'shared/search' %>
	</div>
</div>

app/views/static_pages/recent_updates.html.erb
<h1>Recent Updates</h1>

<%= render_activities(@activities) %>

app/views/static_pages/report.html.erb
<h1><b>Report Generation Module</b></h1>
<div class="jumbotron">
<%= search_form_for @q, url: search_report_static_pages_path do |f| %>
	<div class="row">
		<div class="col-xs-12">
			<%= f.input :project_name_cont, :label => "Project Title:", required: false %>
		</div>
  		<div class="col-xs-6">
  			<%= f.input :status_eq, :collection => ProjectStatus.all, :label_method => :description, :include_blank => true, :label => "Project Status", required: false %>
  		</div>
  		<div class="col-xs-6">
  			<%= f.input :funds_fund_source_in, :collection => FundSource.all.order(:source_name), :label_method => :source_name, :include_blank => true, :label => "Source of fund/s:", required: false %>
  		</div>
  		<div class="col-xs-6">
  			<%= f.input :timeline_actual_end_gteq, :label => "From Completion Date:", :start_year => Date.today.year, :end_year => 1900, :include_blank => true, :as => :date_picker, :placeholder => "DD/MM/YYYY", required: false %>
  		</div>
  		<div class="col-xs-6">
  			<%= f.input :timeline_actual_end_lteq, :label => "To Completion Date:", :start_year => Date.today.year, :end_year => 1900, :include_blank => true, :as => :date_picker, :placeholder => "DD/MM/YYYY", required: false %>
  		</div>
  	</div>
  	<div class="row">
  		<div class="col-xs-12">
  			<%= f.input :university_id_in, :collection => University.all.order(:university_name), :label_method => :university_name, :include_blank => true, :label => "Project of:", required: false, input_html: { multiple: true, :size => 5 } %>
  		</div>
  	</div>
  <%= f.button :submit, :class => "btn btn-success pull-right" %>
<% end %>
</div>
<br>

<%= link_to 'Export to Excel', report_path(params.merge(format: "xlsx")), :class => "pull-right" %>
<% if params[:q] && @projects.count > 0 %>	
	<div class="row">
		<div class="col-xs-12">
			<div class="jumbotron">
				<b>Constituent University:</b>
					<% unless params[:q][:university_id_in].blank? %>
						<% params[:q][:university_id_in].each do |id| %>
							<%= University.find(id).university_name unless id.blank? %> |
						<% end %>
					<% end %>
				<br>
				<b>Number of projects:</b> <%= @projects.count %> <%= ProjectStatus.find(params[:q][:status_eq]).description unless params[:q][:status_eq].blank? %> projects<br>
				<b>From Completion Date:</b> <%= params[:q][:timeline_actual_end_gteq].to_date.try(:strftime, "%d %B %Y") %><br>
				<b>To Completion Date:</b> <%= params[:q][:timeline_actual_end_lteq].to_date.try(:strftime, "%d %B %Y") %><br>
			</div>
		</div>
	</div>
<% end %>
<br>
<div class="row">
	<% @projects.each do |project| %>
		<div class="row">
			<div class="col-xs-12">
				<div class="well">
					<div class="row">
						<div class="col-xs-3">
							Project Code:<br>
							<b><%= project.project_code %></b>
						</div>
						<div class="col-xs-7">
							Project Title:<br>
							<b><%= project.project_name %></b>
						</div>

						<div class="col-xs-2">
							<%= link_to "View details", project %>
						</div>
					</div>
					<br>
					<div class="row">
						<div class="col-xs-6">
							<b>Date of Pre-Procurement: </b><%= project.bidding_preprocurement.strftime("%d %B %Y") if project.bidding_preprocurement %><br>
							<b>Date of Pre-Bidding: </b><%= project.bidding_prebidding.strftime("%d %B %Y") if project.bidding_prebidding %><br>
							<b>Date of Bidding: </b><%= project.bidding_bidding.strftime("%d %B %Y") if project.bidding_bidding %><br>
							<b>Date of Post-Qualification: </b><%= project.bidding_postquali.strftime("%d %B %Y") if project.bidding_postquali %><br>
							<b>Date of Notice of Award: </b><%= project.bidding_award.strftime("%d %B %Y") if project.bidding_award %><br>
							<b>Date of Purchase Order/Contract: </b><%= project.bidding_purchase.strftime("%d %B %Y") if project.bidding_purchase %><br>
							<b>Date of Notice to Proceed: </b><%= project.bidding_proceed.strftime("%d %B %Y") if project.bidding_proceed %><br>
						</div>
						<div class="col-xs-6">
							<b>Period between Bidding Stages (in Calendar Days): </b><br>
							- <%= project.date_period( project.bidding_prebidding, project.bidding_preprocurement ) %><br>
							- <%= project.date_period( project.bidding_bidding, project.bidding_prebidding ) %><br>
							- <%= project.date_period( project.bidding_postquali, project.bidding_bidding ) %><br>
							- <%= project.date_period( project.bidding_award, project.bidding_postquali ) %><br>
							- <%= project.date_period( project.bidding_purchase, project.bidding_award ) %><br>
							- <%= project.date_period( project.bidding_proceed, project.bidding_purchase ) %>
						</div>
					</div>
					<br>
					Date of Completion:
					<b><%= project.timeline_actual_end.try(:strftime, "%d %B %Y") %></b>
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/static_pages/result.html.erb
<br>
<%= render 'shared/search' %>
<br>
<%= render 'shared/projects_list' %>