config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  root 'static_pages#home'

  get '/admin_panel' => 'static_pages#admin_panel'
  get '/report' => 'static_pages#report'
  get '/result' => 'static_pages#result'
  get '/analytics' => 'static_pages#analytics'
  get '/recent_updates' => 'static_pages#recent_updates'

  devise_for :users
  resources :projects do
    resources :project_phases
    resources :project_components
    resources :project_images
  end
  scope "/admin" do
    resources :users
  end
  resources :universities do
    collection do
      match 'search' => 'universities#search', via: [:get, :post], as: :search
    end
  end
  resources :static_pages do
    collection do
      match 'search' => 'static_pages#search', via: [:get, :post], as: :search
      match 'search_report' => 'static_pages#search_report', via: [:get, :post], as: :search_report
      match 'search_analytics' => 'static_pages#search_analytics', via: [:get, :post], as: :search_analytics
      match 'search_users' => 'static_pages#search_users', via: [:get, :post], as: :search_users
    end
  end
  resources :project_statuses
  resources :project_classifications
  resources :fund_sources

  namespace :api do
    api version: 1, module: 'v1' do
      resources :sessions, only: [:create]
      resources :universities, only: [:index, :show]
      resources :projects, only: [:index, :show] do
        resources :project_components, only: [:index, :show]
        resources :project_phases, only: [:index, :show]
        resources :project_images, only: [:index, :show]
      end
    end
  end

  

end

app/views/shared/_navigation.html.erb
<% if user_signed_in? %>
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container-fluid">
		    <div class="navbar-header">
				<%= link_to image_tag('upseal.png', :class => "navbar-brand"), root_path %>
		    </div>
		    <div class="collapse navbar-collapse">
		    	<ul class="nav navbar-nav">
		    		<li class="dropdown">
			     		<%= link_to '<i class="fa fa-university"></i> Universities <i class="fa fa-caret-down"></i>'.html_safe, universities_path, :id => 'campusdrop', :'data-toggle' => 'dropdown', :class => 'dropdown-toggle' %>
			     		<ul class="dropdown-menu">
			     			<% University.all.each do |university| %>
							<li>
								<%= link_to university do %>
								  	<%= icon('university') %> <%= university.university_name %>
								<% end %>
							</li>
							<% end %>
							<% if current_user.admin %>
								<li>
									<%= link_to new_university_path do %>
									<i class="fa fa-plus"></i> Add University
									<% end %>
								</li>
							<% end %>
						</ul>
					</li>
					<li>
			      		<%= link_to report_path do %>
						  	<i class="fa fa-print"></i> Reports
						<% end %>
					</li>
					<li>
			      		<%= link_to analytics_path do %>
						  	<i class="fa fa-pie-chart"></i> Analytics
						<% end %>
					</li>
					<% if current_user.admin %>
						
						<li class="dropdown">
				     		<%= link_to '<i class="fa fa-user-plus"></i> Admin Panel <i class="fa fa-caret-down"></i>'.html_safe, admin_panel_path, :id => 'admindrop', :'data-toggle' => 'dropdown', :class => 'dropdown-toggle' %>
				     		<ul class="dropdown-menu">
								<li> <%=link_to '<i class="fa fa-user-plus"></i> User Management'.html_safe, admin_panel_path %> </li>
								<li> <%=link_to '<i class="fa fa-user-plus"></i> Recent Updates'.html_safe, recent_updates_path %> </li>
								<li> <%=link_to '<i class="fa fa-university"></i> List of Universities'.html_safe, universities_path %> </li>
								<li> <%=link_to '<i class="fa fa-tags"></i> List of Project Classifications'.html_safe, project_classifications_path %> </li>
								<li> <%=link_to '<i class="fa fa-tags"></i> List of Project Statuses'.html_safe, project_statuses_path %> </li>
								<li> <%=link_to '<i class="fa fa-tags"></i> List of Fund Sources'.html_safe, fund_sources_path %> </li>
							</ul>
						</li>
					<% end %>
				</ul>
	      		<ul class="nav navbar-nav navbar-right">
	      			<li>
			      		<%= link_to root_path do %>
						  	<i class="fa fa-home"></i> Home
						<% end %>
					</li>
					<li>
			      		<%= link_to current_user do %>
						  	<i class="fa fa-user"></i> <%= current_user.email %>
						<% end %>
					</li>
					<li>
			      		<%= link_to edit_user_registration_path do %>
						  	<i class="fa fa-gear"></i> Settings
						<% end %>
					</li>
			      	<li class="">
						<%= link_to(destroy_user_session_path, :method=>'delete') do %>
						<i class="fa fa-sign-out"></i> Logout
						<% end %>
					</li>
		      	</ul>
		    </div>
	  	</div>
	</nav>
<% else %>
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container-fluid">
		    <div class="navbar-header">
				<%= link_to image_tag('upseal.png', :class => "navbar-brand"), root_path %>
		    </div>
		    <div class="collapse navbar-collapse">
		    	<ul class="nav navbar-nav">
		    		<li class="dropdown">
			     		<%= link_to '<i class="fa fa-university"></i> Universities <i class="fa fa-caret-down"></i>'.html_safe, universities_path, :id => 'campusdrop', :'data-toggle' => 'dropdown', :class => 'dropdown-toggle' %>
			     		<ul class="dropdown-menu">
			     			<% University.all.each do |university| %>
							<li>
								<%= link_to university do %>
								  	<%= icon('university') %> <%= university.university_name %>
								<% end %>
							</li>
							<% end %>
						</ul>
					</li>
					<li>
			      		<%= link_to report_path do %>
						  	<i class="fa fa-print"></i> Reports
						<% end %>
					</li>
					<li>
			      		<%= link_to analytics_path do %>
						  	<i class="fa fa-pie-chart"></i> Analytics
						<% end %>
					</li>
				</ul>
	      		<ul class="nav navbar-nav navbar-right">
	      			<li>
			      		<%= link_to new_user_session_path do %>
						  	<i class="fa fa-sign-in"></i> Sign in
						<% end %>
					</li>
		      	</ul>
		    </div>
	  	</div>
	</nav>
<% end %>

app/views/shared/_project_shared_panels.html.erb
<!-- Project Status -->
<div class="panel panel-info">
	<div class="panel-heading">
		<b><%= icon('history')%>  Project Status</b>
	</div>
	<div class="panel-body">
		<div class="col-xs-12">
			<b>Classification: </b><%= ProjectClassification.find( project.classification ).description if project.classification.present? %><br>
			<b>Status: </b><%= ProjectStatus.find( project.status ).description if project.status %><br>
			<b>Date Completed: </b><%= project.completed_by.strftime("%d %B %Y") if project.completed_by %><br>
			<b>Last Updated: </b><%= project.updated_at.strftime("%d %B %Y") if project.updated_at %>
		</div>
		<div class="col-xs-12">
			<div class="progress">
			    <div class="progress-bar progress-bar-info active" role="progressbar" aria-valuenow="<%= project.percent_accomplishment %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= project.percent_accomplishment %>%">
			        <span><%= project.percent_accomplishment %>% Complete</span>
			    </div>
			</div>
		</div>
	</div>
</div>


<!-- General Information -->
<div class="panel panel-info">
	<div class="panel-heading">
		<b><%= icon('info-circle')%>  General Information</b>
	</div>
	<div class="panel-body">
		<div class="row">
			<div class="col-xs-6">
				<b>Description:</b><br>
				<div class="well well-sm" style="overflow:auto"><%= simple_format(project.description) %></div>
			</div>
			<div class="col-xs-6">
				<b>Expected Outcome:</b><br>
				<div class="well well-sm" style="overflow:auto"><%= simple_format(project.expected_outcome) %></div>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-12">
				<b>End User/s:</b><br>
				<div class="well well-sm" style="overflow:auto"><%= simple_format(project.end_user) %></div>
			</div>
		</div>
	</div>
</div>

<!-- Bidding Details -->
<div class="panel panel-info">
	<div class="panel-heading">
		<b><%= icon('suitcase')%>  Bidding Details</b>
	</div>
	<div class="panel-body">
		<div class="col-xs-12">

			<div class="progress">
			    <div class="progress-bar progress-bar-info active" role="progressbar" aria-valuenow="<%= project.bidding_percentage %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= project.bidding_percentage %>%">
			        <span><%= project.bidding_percentage %>% Complete</span>
			    </div>
			</div>
		

			<b>Contractor/s: </b><%= project.bidding_contractor %><br>
			<b>Number of Biddings: </b><%= project.bidding_number %><br>

			<br>
			
			<div class="row">
				<div class="col-xs-6">
					<b>Date of Pre-Procurement: </b><%= project.bidding_preprocurement.strftime("%d %B %Y") if project.bidding_preprocurement %><br>
					<b>Date of Pre-Bidding: </b><%= project.bidding_prebidding.strftime("%d %B %Y") if project.bidding_prebidding %><br>
					<b>Date of Bidding: </b><%= project.bidding_bidding.strftime("%d %B %Y") if project.bidding_bidding %><br>
					<b>Date of Post-Qualification: </b><%= project.bidding_postquali.strftime("%d %B %Y") if project.bidding_postquali %><br>
					<b>Date of Notice of Award: </b><%= project.bidding_award.strftime("%d %B %Y") if project.bidding_award %><br>
					<b>Date of Purchase Order/Contract: </b><%= project.bidding_purchase.strftime("%d %B %Y") if project.bidding_purchase %><br>
					<b>Date of Notice to Proceed: </b><%= project.bidding_proceed.strftime("%d %B %Y") if project.bidding_proceed %><br>
				</div>
				<div class="col-xs-6">
					<b>Period between Bidding Stages (in Calendar Days): </b><br>
					- <%= project.date_period( project.bidding_prebidding, project.bidding_preprocurement ) %><br>
					- <%= project.date_period( project.bidding_bidding, project.bidding_prebidding ) %><br>
					- <%= project.date_period( project.bidding_postquali, project.bidding_bidding ) %><br>
					- <%= project.date_period( project.bidding_award, project.bidding_postquali ) %><br>
					- <%= project.date_period( project.bidding_purchase, project.bidding_award ) %><br>
					- <%= project.date_period( project.bidding_proceed, project.bidding_purchase ) %>
				</div>
			</div>
		</div>

		<div class="col-xs-12">
			<br>
			<b>Remarks:</b><br>
			<% unless project.bidding_remarks.blank? %>
				<div class="well well-sm" style="overflow:auto"><%= simple_format(project.bidding_remarks) %></div>
			<% end %>
		</div>
	</div>
</div>
 
<!-- Financial Details -->
<div class="panel panel-info">
	<div class="panel-heading">
		<b><%= icon('money')%>  Financial Details</b>
	</div>
	<div class="panel-body">
		<div class="col-xs-12">
			 <b>Total Budget (PhP): </b><%= number_with_precision( project.financial_budget, precision: 2, delimiter: ',' ) %><br>
			 <b>Contract Price (PhP): </b><%= number_with_precision( project.financial_contract_price, precision: 2, delimiter: ',' ) %><br>
			 <b>Actual Cost (PhP): </b><%= number_with_precision( project.financial_actual_cost, precision: 2, delimiter: ',' ) %><br>
			 <b>Variation Order (PhP): </b><%= number_with_precision( project.financial_variation, precision: 2, delimiter: ',' ) %> 
			 <% unless project.financial_variation.blank? %> || <%= number_with_precision( project.variation_percentage , precision: 2, delimiter: ',' ) %> % of Budget<br>
			 <% end %>
		</div>
		<br>
		<div class="col-xs-12">
			<b>Remarks:</b><br>
			<% unless project.financial_remarks.blank? %>
				<div class="well well-sm" style="overflow:auto"><%= simple_format(project.financial_remarks) %></div>
			<% end %>
		</div>
	</div>
</div>

<!-- Funding Details -->
<div class="panel panel-info">
	<div class="panel-heading">
		<b><%= icon('money')%>  Funding Details</b>
	</div>
	<div class="panel-body">
		<div class="col-xs-12">
			<table class="table table-hover table-responsive">
				<thead>
					<tr>
						<th>Fund Source</th>
						<th>Budget Provided (PhP)</th>
					</tr>
				</thead>
				<tbody>
					<% project.funds.each do |fund| %>
						<tr>
							<td><%= fund.source_name %></td>
							<td><%= number_with_precision( fund.budget, precision: 2, delimiter: ',' ) %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

<!-- Timeline -->
<div class="panel panel-info">
	<div class="panel-heading">
		<b><%= icon('clock-o')%>  Timeline</b>
	</div>
	<div class="panel-body">
		<div class="col-xs-12">
			<b>Target Start Date: </b><%= project.timeline_target_start.strftime("%d %B %Y") if project.timeline_target_start %><br>
			<b>Target Completion Date: </b><%= project.timeline_target_end.strftime("%d %B %Y") if project.timeline_target_end %><br>
			<b>Actual Start Date: </b><%= project.timeline_actual_start.strftime("%d %B %Y") if project.timeline_actual_start %><br>
			<b>Actual Completion Date: </b><%= project.timeline_actual_end.strftime("%d %B %Y") if project.timeline_actual_end %><br>
			<b>Project Duration (in Calendar Days): </b><%= project.get_duration.to_s + " days" if project.get_duration.present? %><br>
			<b>Project Extension (in Calendar Days): </b><%= project.timeline_extension.to_s + " days" if project.timeline_extension.present? %><br>
		</div>
		<br>
		<div class="col-xs-12">
			<b>Remarks:</b><br>
			<% unless project.timeline_remarks.blank? %>
				<div class="well well-sm" style="overflow:auto"><%= simple_format(project.timeline_remarks) %></div>
			<% end %>
		</div>
	</div>
</div>

app/views/shared/_projects_list.html.erb
<%= link_to '<i class="fa fa-plus"></i> New Project'.html_safe, new_project_path, :class => "pull-right" %>
<table class="table table-hover table-responsive">
  <thead>
    <tr>
      <th>Project Code</th>
      <th>Project Name</th>
      <th>Description</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td style="text-align: left; word-wrap: break-word;min-width: 160px;max-width: 160px;white-space:normal;"><%= project.project_code %></td>
        <td style="text-align: left; word-wrap: break-word;min-width: 160px;max-width: 160px;white-space:normal;"><%= project.project_name %></td>
        <td style="text-align: left; word-wrap: break-word;min-width: 160px;max-width: 160px;white-space:normal;"><%= project.description %></td>
        <td style="text-align: right; word-wrap: break-word;min-width: 160px;max-width: 160px;white-space:normal;"><%= link_to "View details", project %><br><%= link_to "View images", project_project_images_path(project) unless project.project_images.blank? %></td>
        </tr>
    <% end %>
  </tbody>
</table>
<div class="text-center">
  <%= will_paginate @projects, renderer: BootstrapPagination::Rails %>
</div>

app/views/shared/_search.html.erb
<div id="accordion" class="panel panel-info">
	<div class="panel-heading">
		<b><span class="accordion-toggle" data-toggle="collapse" data-target="#collapseSearch" data-parent="#accordion" href="#collapseSearch"><%= icon('search')%> Search:</span></b>
	</div>
	<div id="collapseSearch" class="panel-collapse collapse">
		<div class="panel-body">
			<%= search_form_for @q, url: search_static_pages_path do |f| %>
				<div class="row">
					<div class="col-xs-2">
			  			<%= f.input :project_code_cont, :label => "Project Code:", required: false %>
			  		</div>
			  		<div class="col-xs-5">
			  			<%= f.input :project_name_or_project_components_component_name_or_project_phases_phase_name_cont, :label => "Project Title:", required: false %>
			  		</div>
			  		<div class="col-xs-5">
			  			<%= f.input :description_cont, :label => "Project Description:", required: false %>
			  		</div>
			  	</div>

			  	<div class="row">
			  		<div class="col-xs-3">
			  			<%= f.input :status_eq, :collection => ProjectStatus.all, :label_method => :description, :include_blank => true, :label => "Project Status", required: false %>
			  		</div>
			  		<div class="col-xs-3">
			  			<%= f.input :university_id_eq, :collection => University.all.order(:university_name), :label_method => :university_name, :include_blank => true, :label => "Project of:", required: false %>
			  		</div>
					<div class="col-xs-3">
			  			<%= f.input :timeline_actual_end_gteq, :label => "From Completion Date:", :start_year => Date.today.year, :end_year => 1900, :include_blank => true, :as => :date_picker, :placeholder => "DD/MM/YYYY", required: false %>
			  		</div>
			  		<div class="col-xs-3">
			  			<%= f.input :timeline_actual_end_lteq, :label => "To Completion Date:", :start_year => Date.today.year, :end_year => 1900, :include_blank => true, :as => :date_picker, :placeholder => "DD/MM/YYYY", required: false %>
			  		</div>
			  	</div>

			  	<div class="row">
			  		<div class="col-xs-6">
			  			<%= f.input :bidding_contractor_cont, :label => "Contractor/s:", required: false %>
			  		</div>
			  		<div class="col-xs-6">
			  			<%= f.input :funds_fund_source_in, :collection => FundSource.all.order(:source_name), :label_method => :source_name, :include_blank => true, :label => "Source of fund/s:", required: false %>
			  		</div>
			  	</div>
			  	<div class="row">
			  		<div class="col-xs-3">
			  			<%= f.input :financial_budget_gteq, :label => "Min. Budget", required: false %>
			  		</div>
			  		<div class="col-xs-3">
			  			<%= f.input :financial_budget_lteq, :label => "Max. Budget", required: false %>
			  		</div>
			  		<div class="col-xs-3">
			  			<%= f.input :percent_accomplishment_gteq, :label => "Min. % Accomplishment", required: false %>
			  		</div>
			  		<div class="col-xs-3">
			  			<%= f.input :percent_accomplishment_lteq, :label => "Max. % Accomplishment", required: false %>
			  		</div>
			  	</div>
			  <%= f.button :submit, :class => "btn btn-success pull-right" %>
			<% end %>
		</div>
	</div>
</div>

<script>
$("#accordion").on("shown.bs.collapse", function () {
    var myEl = $(this).find('.collapse.in').prev('.panel-heading');

    $('html, body').animate({
        scrollTop: $(myEl).offset().top
    }, 500);
});
</script>

app/views/shared/_unauthorized.html.erb
<div class="jumbotron">
  <h1>Unauthorized</h1>
  <p>You do not have the required permissions to access this page.</p>
  <%= link_to 'Back', "javascript:history.back()", :class => "pull-right" %>
</div>

app/views/shared/_university_selector.html.erb
<div class="row">
	<div class="dropdown col-xs-12">
		<button class="btn btn-success dropdown-toggle col-xs-12" type="button" id="univDropdown" data-toggle="dropdown" aria-expanded="true">
			Select a CU <%= icon('caret-down') %>
		</button>
		<ul class="dropdown-menu col-xs-12" style="height: auto; max-height: 180px; overflow-x: hidden;" role="menu" aria-labelledby="dropdownMenu1">
			<% @university_list.each do |university| %>
				<li>
					<%= link_to university do %>
					  	<%= icon('university') %> <%= university.university_name %>
					<% end %>
				</li>
			<% end %>
		</ul>
	</div>
</div>