config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  root 'static_pages#home'

  get '/admin_panel' => 'static_pages#admin_panel'
  get '/report' => 'static_pages#report'
  get '/result' => 'static_pages#result'
  get '/analytics' => 'static_pages#analytics'
  get '/recent_updates' => 'static_pages#recent_updates'

  devise_for :users
  resources :projects do
    resources :project_phases
    resources :project_components
    resources :project_images
  end
  scope "/admin" do
    resources :users
  end
  resources :universities do
    collection do
      match 'search' => 'universities#search', via: [:get, :post], as: :search
    end
  end
  resources :static_pages do
    collection do
      match 'search' => 'static_pages#search', via: [:get, :post], as: :search
      match 'search_report' => 'static_pages#search_report', via: [:get, :post], as: :search_report
      match 'search_analytics' => 'static_pages#search_analytics', via: [:get, :post], as: :search_analytics
      match 'search_users' => 'static_pages#search_users', via: [:get, :post], as: :search_users
    end
  end
  resources :project_statuses
  resources :project_classifications
  resources :fund_sources

  namespace :api do
    api version: 1, module: 'v1' do
      resources :sessions, only: [:create]
      resources :universities, only: [:index, :show]
      resources :projects, only: [:index, :show] do
        resources :project_components, only: [:index, :show]
        resources :project_phases, only: [:index, :show]
        resources :project_images, only: [:index, :show]
      end
    end
  end

  

end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :university
	validates :project_name, presence: true
	validates :project_code, presence: true, uniqueness: true
	validates :financial_budget, presence: true, numericality: { :greater_than => 0 }
	validates :university_id, presence: true
	validates :status, presence: true
	validates :classification, presence: true

	has_many :project_images, :dependent => :destroy
	has_many :project_components, :dependent => :destroy
	has_many :project_phases, :dependent => :destroy

	#has_many :contractors, as: :contractable
	#has_many :fund_sources, as: :fundable
	has_many :fundable_projects, :dependent => :destroy
  	has_many :fund_sources, through: :fundable_projects

  	has_many :funds, as: :fundable, :dependent => :destroy

	validate :project_images_count_within_bounds
	accepts_nested_attributes_for :project_images, :project_components, :project_phases, :fund_sources
	accepts_nested_attributes_for :funds, :reject_if => :all_blank, :allow_destroy => true

	after_save :update_status

	acts_as_xlsx
	include PublicActivity::Model
  	tracked owner: Proc.new { |controller, model| controller.current_user ? controller.current_user : nil }

	def variation_percentage
		if financial_variation.present?
			if financial_contract_price.present?
				return 100*financial_variation/financial_contract_price
			else
				if financial_budget.present?
					return 100*financial_variation/financial_budget
				end
			end
		end
	end

	def get_duration
		if timeline_actual_start.present? && timeline_actual_end.present?
			return (timeline_actual_end.to_date - timeline_actual_start.to_date).to_i
		end
	end

	def date_period( date_from, date_to )
		if date_from.present? && date_to.present?
			days = (date_from.to_date - date_to.to_date).to_i
			modifier = " days"
			modifier = " day" unless days > 1
			return days.to_s + modifier
		else
			return ""
		end
	end
	
	def bidding_percentage
		bid_percent = 0.00
		step_value = 100.00 / 7.00
		bid_percent += step_value if bidding_preprocurement.present?
		bid_percent += step_value if bidding_prebidding.present?
		bid_percent += step_value if bidding_bidding.present?
		bid_percent += step_value if bidding_postquali.present?
		bid_percent += step_value if bidding_award.present?
		bid_percent += step_value if bidding_purchase.present?
		bid_percent += step_value if bidding_proceed.present?
		return bid_percent.round(2)
	end

	private
		def project_images_count_within_bounds
	    	return if project_images.blank?
	    	errors.add(:project_images, "The project has reached its image limit.") if project_images.size > 15
		end

		def update_status
			if self.percent_accomplishment.present? && self.percent_accomplishment >= 100
				self.update_column(:status, 1)
			end

			if self.status == 1
				self.update_column(:percent_accomplishment, 100)
			end
		end
end

app/controllers/api/v1/projects_controller.rb
class Api::V1::ProjectsController < Api::V1::BaseController
  before_action :set_project, only: [:show]

  def index
    expose Project.all, only: [:id, :project_name, :project_code]
  end

  def show
    # expose({ 
    #   project: @project, 
    #   project_components: @project.project_components,
    #   project_phases: @project.project_phases,
    #   project_images: @project.project_images
    # })
  
    expose @project, :include => {
      :funds => { only: [ :budget ], methods: :source_name },
      :project_components => { only: [ :id, :component_name ] },
      :project_phases => { only: [ :id, :phase_name ] }      
    }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end
end

app/controllers/projects_controller.rb
  class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @university = University.find( @project.university_id )
    @project_images = @project.project_images.paginate(:page => params[:page], :per_page => 9)
    @project_components = @project.project_components.paginate(:page => params[:page], :per_page => 5)
    @project_phases = @project.project_phases.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /projects/new
  def new
    @project = Project.new    
    @project.funds.build
    @project_image = @project.project_images.build
  end

  # GET /projects/1/edit
  def edit
    @project.funds.build unless @project.funds.count > 0
    @project_image = @project.project_images.build unless @project.project_images.count > 0
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        if params[:project_images]
          params[:project_images].each do |a|
            unless @project.project_images.count > 15
              @project_image = @project.project_images.create(:image => a, :project_id => @project.id)
            end
          end
        end
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        if params[:project_images]
          params[:project_images].each do |a|
            unless @project.project_images.count > 15
              @project_image = @project.project_images.create(:image => a, :project_id => @project.id)
            end
          end
        end
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @redirect_url = University.find( @project.university_id )
    @project.destroy
    respond_to do |format|
      format.html { redirect_to @redirect_url, notice: 'Project was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:university_id, :project_name, :project_code, :description, :expected_outcome, :end_user, :percent_accomplishment, :percent_accomplishment_by, :remarks, :has_components, :has_phases, :bidding_contractor, :bidding_number, :bidding_preprocurement, :bidding_prebidding, :bidding_bidding, :bidding_postquali, :bidding_award, :bidding_purchase, :bidding_proceed, :bidding_remarks, :financial_source, :financial_budget, :financial_contract_price, :financial_actual_cost, :financial_variation, :financial_remarks, :timeline_target_start, :timeline_target_end, :timeline_actual_start, :timeline_actual_end, :timeline_duration, :timeline_extension, :timeline_remarks, :status, :classification, :completed_by, :fund_source_ids => [], project_images_attributes: [ :id, :project_id, :image, :description, :_destroy], funds_attributes: [ :id, :fund_source, :budget, :_destroy] )
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project, html: {multipart: true}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

  	<div class="panel panel-info">
  		<div class="panel-heading">
  			<b>Project Status</b>
  		</div>
  		<div class="panel-body">
  			<div class="col-xs-6">
  				<%= f.input :status, :collection => ProjectStatus.all, :label_method => :description, :include_blank => false, :label => "Project Status" %>
  			</div>
  			<div class="col-xs-6">
  				<%= f.input :classification, :collection => ProjectClassification.all, :label_method => :description, :include_blank => false, :label => "Project Classification" %>
  			</div>

  			<div class="col-xs-4">
				<%= f.input :percent_accomplishment, :label => "Percent Accomplisment:" %>
			</div>
  			<div class="col-xs-4">
  				<%= f.input :completed_by, :label => "Completed By:", :start_year => Date.today.year, :end_year => 1900, :include_blank => true, :as => :date_picker, :placeholder => "DD/MM/YYYY" %>
  			</div>
			<div class="col-xs-4">
				<%= f.input :percent_accomplishment_by, :label => "Percent Accomplished By:", :start_year => Date.today.year, :end_year => 1900, :include_blank => true, :as => :date_picker, :placeholder => "DD/MM/YYYY" %>
			</div>
  		</div>
  	</div>

	<div class="panel panel-info">
		<div class="panel-heading">
			<b>General Information</b>
		</div>
		<div class="panel-body">

			<div class="col-xs-12">
				<% if current_user.admin %>
					<%= f.input :university_id, :collection => University.all.order(:university_name), :label_method => :university_name, :include_blank => false, :label => "Project of:" %>
				<% else %>
					<%= f.input :university_id, :collection => current_user.universities.order(:university_name), :label_method => :university_name, :include_blank => false, :label => "Project of:" %>
				<% end %>
			</div>

		  	<div class="col-xs-6">
		  		<%= f.input :project_name, :label => "Project Name:" %>
		  	</div>
		  	<div class="col-xs-6">
				<%= f.input :project_code, :label => "Project Code:" %>
			</div>

			<div class="col-xs-6">
				<%= f.input :description, :label => "Description:", :input_html => {:rows => 5} %>
			</div>
			<div class="col-xs-6">
				<%= f.input :expected_outcome, :label => "Expected Outcome:", :input_html => {:rows => 5} %>
			</div>

			<div class="col-xs-12">
				<%= f.input :end_user, :label => "End User/s:", :input_html => {:rows => 5} %>
			</div>

			<div class="col-xs-12">
				<%= f.input :remarks, :label => "Remarks:", :input_html => {:rows => 5} %>
			</div>
			
			<div class="col-xs-6">
				<%= f.input :has_components, :label => "Project has components" %>
			</div>
			<div class="col-xs-6">
				<%= f.input :has_phases, :label => "Project has phases" %>
			</div>
		</div>
	</div>

	<div class="panel panel-info">
		<div class="panel-heading">
			<b>Bidding Details</b>
		</div>
		<div class="panel-body">
			<div class="col-xs-12">
				<%= f.input :bidding_contractor, :label => "Contractor/s:", :input_html => {:rows => 3} %>
			</div>
			<div class="col-xs-6">
				<%= f.input :bidding_number, :label => "Number of Biddings:" %>
			</div>
			<div class="col-xs-6">
				<%= f.input :bidding_preprocurement, :label => "Date of Pre-Procurement:", :start_year => Date.today.year, :end_year => 1900, :include_blank => true, :as => :date_picker, :placeholder => "DD/MM/YYYY"  %>
			</div>

			<div class="col-xs-6">
				<%= f.input :bidding_prebidding, :label => "Date of Pre-Bidding:", :start_year => Date.today.year, :end_year => 1900, :include_blank => true, :as => :date_picker, :placeholder => "DD/MM/YYYY"  %>
			</div>
			<div class="col-xs-6">
				<%= f.input :bidding_bidding, :label => "Date of Bidding:", :start_year => Date.today.year, :end_year => 1900, :include_blank => true, :as => :date_picker, :placeholder => "DD/MM/YYYY"  %>
			</div>

			<div class="col-xs-6">
				<%= f.input :bidding_postquali, :label => "Date of Post-Qualification:", :start_year => Date.today.year, :end_year => 1900, :include_blank => true, :as => :date_picker, :placeholder => "DD/MM/YYYY"  %>
			</div>
			<div class="col-xs-6">
				<%= f.input :bidding_award, :label => "Date of Notice of Award:", :start_year => Date.today.year, :end_year => 1900, :include_blank => true, :as => :date_picker, :placeholder => "DD/MM/YYYY"  %>
			</div>

			<div class="col-xs-6">
				<%= f.input :bidding_purchase, :label => "Date of Purchase Order/Contract:", :start_year => Date.today.year, :end_year => 1900, :include_blank => true, :as => :date_picker, :placeholder => "DD/MM/YYYY"  %>
			</div>
			<div class="col-xs-6">
				<%= f.input :bidding_proceed, :label => "Date of Notice to Proceed:", :start_year => Date.today.year, :end_year => 1900, :include_blank => true, :as => :date_picker, :placeholder => "DD/MM/YYYY"  %>
			</div>

			<div class="col-xs-12">
				<%= f.input :bidding_remarks, :label => "Remarks:", :input_html => {:rows => 5} %>
			</div>
		</div>
	</div>

	<div class="panel panel-info">
		<div class="panel-heading">
			<b>Financial Details</b>
		</div>
		<div class="panel-body">
			<div class="col-xs-6">
				<%= f.input :financial_budget, :label => "Budget (PhP):" %>
			</div>
			<div class="col-xs-6">
				<%= f.input :financial_contract_price, :label => "Contract Price (PhP):" %>
			</div>
			<div class="col-xs-6">
				<%= f.input :financial_actual_cost, :label => "Actual Cost (PhP):" %>
			</div>
			<div class="col-xs-6">
				<%= f.input :financial_variation, :label => "Variation Order (PhP):" %>
			</div>
			<div class="col-xs-12">
				<%= f.input :financial_remarks, :label => "Remarks:", :input_html => {:rows => 5}, :placeholder => "Donors and Government Agencies names should also be listed here if applicable." %>
			</div>
		</div>
	</div>

	<div class="panel panel-info">
		<div class="panel-heading">
			<b>Funding Detail</b>
		</div>
		<div class="panel-body">

			<%= f.simple_fields_for :funds do |fund| %>
					<%= render 'fund_fields', :f => fund %>
			<% end %>
			
			<div class="col-xs-12">
				<%= link_to_add_association '<i class="fa fa-plus"></i> Add source'.html_safe, f, :funds %>
			</div>

		</div>
	</div>

	<div class="panel panel-info">
		<div class="panel-heading">
			<b>Timeline</b>
		</div>
		<div class="panel-body">
			<div class="col-xs-6">
				<%= f.input :timeline_target_start, :label => "Target Start Date:", :start_year => Date.today.year, :end_year => 1900, :include_blank => true, :as => :date_picker, :placeholder => "DD/MM/YYYY" %>
			</div>
			<div class="col-xs-6">
				<%= f.input :timeline_target_end, :label => "Target Completion Date:", :start_year => Date.today.year, :end_year => 1900, :include_blank => true, :as => :date_picker, :placeholder => "DD/MM/YYYY" %>
			</div>
			<div class="col-xs-6">
				<%= f.input :timeline_actual_start, :label => "Actual Start Date:", :start_year => Date.today.year, :end_year => 1900, :include_blank => true, :as => :date_picker, :placeholder => "DD/MM/YYYY" %>
			</div>
			<div class="col-xs-6">
				<%= f.input :timeline_actual_end, :label => "Actual Completion Date:", :start_year => Date.today.year, :end_year => 1900, :include_blank => true, :as => :date_picker, :placeholder => "DD/MM/YYYY" %>
			</div>	
			<div class="col-xs-6">
				<%= f.input :timeline_duration, :label => "Project Duration (in Calendar days):", :readonly => true, :input_html => {value: f.object.get_duration} %>
			</div>
			<div class="col-xs-6">
				<%= f.input :timeline_extension, :label => "Project Extension (in Calendar days):" %>
			</div>
			<div class="col-xs-12">
				<%= f.input :timeline_remarks, :label => "Remarks:", :input_html => {:rows => 5} %>
			</div>
		</div>
	</div>

	<div class="panel panel-info">
		<div class="panel-heading">
			<b>Gallery</b>
		</div>
		<div class="panel-body">
			<% if @project.project_images.count > 15 %>
				<b>This project has reached its image limit. Please delete some images if you want to upload more.</b>
			<% else %>
				<div class="col-xs-12">
					<b>Add Images (Maximum of 2MB per image): </b><br>
					<%= file_field_tag "project_images[]", type: :file, multiple: true %>
				</div>
			<% end %>
		</div>
	</div>

  </div>

  <div class="form-actions">
    <%= f.button :submit, "Save Updates" %>
  </div>
<% end %>

app/views/projects/_fund_fields.html.erb
<div class="nested-fields">
	<div class="col-xs-12">
		<div class="col-xs-5">
			<%= f.input :fund_source, :collection => FundSource.all.order(:source_name), :label_method => :source_name, :include_blank => true, :label => "Fund Source" %>
		</div>
		<div class="col-xs-5">
			<%= f.input :budget, :label => "Budget (PhP)" %>
		</div>
		<div class="col-xs-2">
			<%= link_to_remove_association '<i class="fa fa-remove"></i> Remove'.html_safe, f %>
		</div>
	</div>
</div>

app/views/projects/edit.html.erb
<h1>Editing <%= link_to @project.project_name, @project %></h1>
<% if current_user.admin || !current_user.universities.where(:id => @project.university_id ).blank? %>
	<%= render 'form' %>
<% else %>
	<%= render 'shared/unauthorized' %>
<% end %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', "javascript:history.back()" %>

app/views/projects/index.html.erb
<br>
<%= render 'shared/university_selector' %>
<br><br>
<div class="col-xs-12">
	<div class="panel panel-success text-center">
		<div class="panel-heading">
			<h1>All Projects</h1>
		</div>
		<div class="panel-body">
			<%= render 'shared/projects_list' %>
		</div>
	</div>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>
<%= link_to 'Back', "javascript:history.back()" %>

app/views/projects/show.html.erb
<div class="panel panel-success">
	<div class="panel-heading text-center">
		<h3><%= @project.project_name %></h3>
		<b><%= @project.project_code %> - <%= link_to @university.university_name, @university %></b>
	</div>
	<div class="panel-body">
		<p id="notice"><%= notice %></p>
		<p class="text-right">
			<% if user_signed_in? %>
	 		<% if current_user.admin || !current_user.universities.where(:id => @project.university_id ).blank? %>
				<%= link_to 'Edit', edit_project_path(@project) %> |
				<%= link_to 'Delete', @project, method: :delete, data: { confirm: 'Are you sure you want to delete this project?' } %> |
			<% end %>
			<% end %>
			<%= link_to 'Back', "javascript:history.back()" %>
		</p>
		
		<%= render 'shared/project_shared_panels', :project => @project %>

		<% if @project.has_components %>
			<div class="panel panel-info">
				<div class="panel-heading">
					<b><%= icon('tasks')%>  Project Components</b>
				</div>
				<div class="panel-body">
					<div class="col-xs-12">
						<div class="pull-right">
							<% if user_signed_in? %>
							<% if current_user.admin || !current_user.universities.where(:id => @project.university_id ).blank? %>
								<%= link_to '<i class="fa fa-plus"></i> Add new Project Component'.html_safe, new_project_project_component_path(@project) %> |
							<% end %>
							<% end %>
							<%= link_to '<i class="fa fa-search"></i> View all Project Components'.html_safe, project_project_components_path(@project) %> 
						</div>
						<table class="table table-hover table-responsive">
						  <thead>
						    <tr>
						      <th>Component Name</th>
						      <th>Description</th>
						      <th></th>
						    </tr>
						  </thead>
						  <tbody>
						    <% @project_components.each do |component| %>
						      <tr>
						        <td style="text-align: left; word-wrap: break-word;max-width: 220px;white-space:normal;"><%= component.component_name %></td>
						        <td style="text-align: left; word-wrap: break-word;max-width: 220px;white-space:normal;"><%= component.description %></td>
						        <td style="text-align: right; word-wrap: break-word;max-width: 200px;white-space:normal;"><%= link_to "View details", project_project_component_path(@project, component), :class => "btn btn-small btn-info" %></td>    
						      </tr>
						    <% end %>
						  </tbody>
						</table>
						<div class="text-center">
						  <%= will_paginate @project_components, renderer: BootstrapPagination::Rails %>
						</div>
					</div>
				</div>
			</div>
		<% end %>

		<% if @project.has_phases %>
			<div class="panel panel-info">
				<div class="panel-heading">
					<b><%= icon('tasks')%>  Project Phases</b>
				</div>
				<div class="panel-body">
					<div class="col-xs-12">
						<div class="pull-right">
							<% if user_signed_in? %>
							<% if current_user.admin || !current_user.universities.where(:id => @project.university_id ).blank? %>
								<%= link_to '<i class="fa fa-plus"></i> Add new Project Phase'.html_safe, new_project_project_phase_path(@project) %> |
							<% end %>
							<% end %>
							<%= link_to '<i class="fa fa-search"></i> View all Project Phases'.html_safe, project_project_phases_path(@project) %> 
						</div>
						<table class="table table-hover table-responsive">
						  <thead>
						    <tr>
						      <th>Phase Name</th>
						      <th>Description</th>
						      <th></th>
						    </tr>
						  </thead>
						  <tbody>
						    <% @project_phases.each do |phase| %>
						      <tr>
						        <td style="text-align: left; word-wrap: break-word;max-width: 220px;white-space:normal;"><%= phase.phase_name %></td>
						        <td style="text-align: left; word-wrap: break-word;max-width: 220px;white-space:normal;"><%= phase.description %></td>
						        <td style="text-align: right; word-wrap: break-word;max-width: 200px;white-space:normal;"><%= link_to "View details", project_project_phase_path(@project, phase), :class => "btn btn-small btn-info" %></td>    
						      </tr>
						    <% end %>
						  </tbody>
						</table>
						<div class="text-center">
						  <%= will_paginate @project_phases, renderer: BootstrapPagination::Rails %>
						</div>
					</div>
				</div>
			</div>
		<% end %>

		<div class="panel panel-info">
			<div class="panel-heading">
				<b><%= icon('quote-right')%>  General Remarks</b>
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-xs-12">
						<%= simple_format(@project.remarks) %>
					</div>
				</div>
			</div>
		</div>

		<div class="panel panel-info">
			<div class="panel-heading">
				<b><%= icon('image')%>  Gallery</b>
			</div>
			<div class="panel-body">
				<div class="pull-right">
					<% if user_signed_in? %>
					<% if current_user.admin || !current_user.universities.where(:id => @project.university_id ).blank? %>
						<%= link_to '<i class="fa fa-plus"></i> Add new Project Image'.html_safe, edit_project_path(@project) %> |
					<% end %>
					<% end %>
					<%= link_to '<i class="fa fa-search"></i> View all Project Images'.html_safe, project_project_images_path(@project) %> 
				</div>
				<div class="col-xs-12">
					<% @project_images.each_with_index do |image, index| %>
  						<% if index % 3 == 0 %>
  							<div class="row">
  							</div>
  						<% end %>
						<div class="col-xs-4">
							<%= link_to project_project_image_path(@project, image) do %>
								<%= image_tag image.image_url(:thumbnail), :class => "img-responsive center-image" %>
							<% end %>
							<br>
  						</div>
					<% end %>
				</div>
				<%= will_paginate @project_images, renderer: BootstrapPagination::Rails, :class => "pull-right" %>
			</div>
		</div>
	 	<div class="pull-right">
	 		<% if user_signed_in? %>
	 		<% if current_user.admin || !current_user.universities.where(:id => @project.university_id ).blank? %>
				<%= link_to 'Edit', edit_project_path(@project) %> |
				<%= link_to 'Delete', @project, method: :delete, data: { confirm: 'Are you sure you want to delete this project?' } %> |
			<% end %>
			<% end %>
			<%= link_to 'Back', "javascript:history.back()" %>
		</div>
 	</div>
 </div>