config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  root 'static_pages#home'

  get '/admin_panel' => 'static_pages#admin_panel'
  get '/report' => 'static_pages#report'
  get '/result' => 'static_pages#result'
  get '/analytics' => 'static_pages#analytics'
  get '/recent_updates' => 'static_pages#recent_updates'

  devise_for :users
  resources :projects do
    resources :project_phases
    resources :project_components
    resources :project_images
  end
  scope "/admin" do
    resources :users
  end
  resources :universities do
    collection do
      match 'search' => 'universities#search', via: [:get, :post], as: :search
    end
  end
  resources :static_pages do
    collection do
      match 'search' => 'static_pages#search', via: [:get, :post], as: :search
      match 'search_report' => 'static_pages#search_report', via: [:get, :post], as: :search_report
      match 'search_analytics' => 'static_pages#search_analytics', via: [:get, :post], as: :search_analytics
      match 'search_users' => 'static_pages#search_users', via: [:get, :post], as: :search_users
    end
  end
  resources :project_statuses
  resources :project_classifications
  resources :fund_sources

  namespace :api do
    api version: 1, module: 'v1' do
      resources :sessions, only: [:create]
      resources :universities, only: [:index, :show]
      resources :projects, only: [:index, :show] do
        resources :project_components, only: [:index, :show]
        resources :project_phases, only: [:index, :show]
        resources :project_images, only: [:index, :show]
      end
    end
  end

  

end

app/models/project_classification.rb
class ProjectClassification < ActiveRecord::Base
end

app/controllers/project_classifications_controller.rb
class ProjectClassificationsController < ApplicationController
  before_action :set_project_classification, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /project_classifications
  # GET /project_classifications.json
  def index
    @project_classifications = ProjectClassification.all
  end

  # GET /project_classifications/1
  # GET /project_classifications/1.json
  def show
  end

  # GET /project_classifications/new
  def new
    @project_classification = ProjectClassification.new
  end

  # GET /project_classifications/1/edit
  def edit
  end

  # POST /project_classifications
  # POST /project_classifications.json
  def create
    @project_classification = ProjectClassification.new(project_classification_params)

    respond_to do |format|
      if @project_classification.save
        format.html { redirect_to project_classifications_path, notice: 'Project classification was successfully created.' }
        format.json { render :show, status: :created, location: @project_classification }
      else
        format.html { render :new }
        format.json { render json: @project_classification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /project_classifications/1
  # PATCH/PUT /project_classifications/1.json
  def update
    respond_to do |format|
      if @project_classification.update(project_classification_params)
        format.html { redirect_to project_classifications_path, notice: 'Project classification was successfully updated.' }
        format.json { render :show, status: :ok, location: @project_classification }
      else
        format.html { render :edit }
        format.json { render json: @project_classification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_classifications/1
  # DELETE /project_classifications/1.json
  def destroy
    @project_classification.destroy
    respond_to do |format|
      format.html { redirect_to project_classifications_url, notice: 'Project classification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_classification
      @project_classification = ProjectClassification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_classification_params
      params.require(:project_classification).permit(:description)
    end
end

app/helpers/project_classifications_helper.rb
module ProjectClassificationsHelper
end

app/views/project_classifications/_form.html.erb
<%= simple_form_for(@project_classification) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn btn-success" %>
  </div>
<% end %>

app/views/project_classifications/edit.html.erb
<h1>Editing Project Classification</h1>
<% if current_user.admin %>
	<%= render 'form' %>
<% else %>
	<%= render 'shared/unauthorized' %>
<% end %>
<%= link_to 'Back', "javascript:history.back()" %>

app/views/project_classifications/index.html.erb
<% if current_user.admin %>
<p id="notice"><%= notice %></p>
</br>
<h1><b>List of Project Classifications</b></h1>
<%= link_to '<i class="fa fa-plus"></i> New Project Classification'.html_safe, new_project_classification_path, :class => "pull-right" %>
<table class="table table-hover table-responsive">
  <thead>
    <tr>
      <th>Description</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @project_classifications.each do |project_classification| %>
      <tr>
        <td><%= project_classification.description %></td>
        <td style="text-align: right;">
           <%= link_to 'Edit', edit_project_classification_path(project_classification) %> | <%= link_to 'Destroy', project_classification, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
 <%= render 'shared/unauthorized' %>
<% end %>

app/views/project_classifications/new.html.erb
<h1>New Project Classification</h1>
<% if current_user.admin %>
	<%= render 'form' %>
<% else %>
	<%= render 'shared/unauthorized' %>
<% end %>
<%= link_to 'Back', "javascript:history.back()" %>

app/views/project_classifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @project_classification.description %>
</p>

<%= link_to 'Edit', edit_project_classification_path(@project_classification) %> |
<%= link_to 'Back', project_classifications_path %>